#ifndef __COMMON_H__
#define __COMMON_H__

//#define GLUT_NO_LIB_PRAGMA	// disable automatic glut linking

// These defined values will be generated by a code generating module
// The ideal block sizes chosen by an automated test suite
// The cell size defined by the input
#define HORIZONTAL_BLOCKSIZEX 96
#define HORIZONTAL_BLOCKSIZEY 2

#define VERTICAL_BLOCKSIZEX 16
#define VERTICAL_BLOCKSIZEY 24

#define CELLSX 1024
#define CELLSY 1024

#include "cuda.h"
#include "cuda_runtime.h"
#include "cuda_runtime_api.h"
#include "device_launch_parameters.h"
#include "params.h"
#include "Timer.h"

#endif