#ifndef __COMMON_H__
#define __COMMON_H__

// These defined values will be generated by a code generating module
// The ideal block sizes chosen by an automated test suite
// The cell size defined by the input
#define BLOCKSIZEX 192 //192
#define BLOCKSIZEY 384 //384

#define HORIZONTAL_BLOCKSIZEX 96	//96
#define HORIZONTAL_BLOCKSIZEY 2		//2

#define VERTICAL_BLOCKSIZEX 32	//16 //32
#define VERTICAL_BLOCKSIZEY 12	//24 //12

#define CELLSX 256
#define CELLSY 256

#include "cuda.h"
#include "cuda_runtime.h"
#include "cuda_runtime_api.h"
#include "device_launch_parameters.h"
#include "Timer.h"

#include "params.h"

#endif //-Xptxas -dlcm=cg 